api_platform:
    mapping:
        paths: 
            - '%kernel.project_dir%/config/api_platform/resources'
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
        api_keys:
            JWT:
                name: Authorization
                type: header
    title: 'Symfony API'
    version: '1.0.1'
    show_webby: false