App\Entity\User:
  attributes:
    normalization_context:
      groups: [user_read]
  collectionOperations:
    register:
      method: POST
      path: /users/register
      controller: App\Api\Action\User\Register
      denormalization_context:
        groups: [user_post]
      openapi_context:
        summary: Register a new user
        responses: # Aquí especificas explícitamente las respuestas que esperas
          '201': { description: 'User registered successfully' }
          '400': { description: 'Invalid input' }
          '422': { description: 'Unprocessable entity' }
    resend_activation_email:
      method: POST
      path: /users/resend_activation_email
      controller: App\Api\Action\User\ResendActivationEmail
      deserialize: false
      openapi_context:
        summary: Sends activation email to inactive user
        requestBody:
          content:
            application/json:
              schema:
                type: object
                properties:
                  email:
                    type: string
                    required: true
        responses:
          200:
            description: OK
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    message:
                      type: string
          201: { description: 'Not used' }         
    login:
      method: POST
      route_name: api_login_check
      openapi_context:
        summary: Login a user in the API
        requestBody:
          content:
            application/json:
              schema:
                type: object
                properties:
                  email:
                    type: string
                    required: true
                  password:
                    type: string
                    required: true
        responses:
          200:
            description: OK
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    token:
                      type: string
          '201': { description: 'Not used' }`
    request_reset_password:
      method: POST
      path: /users/request_reset_password
      controller: App\Api\Action\User\RequestResetPassword
      deserialize: false
      openapi_context:
        summary: Request a password reset with a URL
        requestBody:
          content:
            application/json:
              schema:
                type: object
                properties:
                  email:
                    type: string
                    required: true
        responses:
          200:
            description: OK
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    message:
                      type: string
          201: { description: 'Not used' }
  itemOperations:
    get:
      method: GET
    activate:
      method: PUT
      path: /users/{id}/activate
      controller: App\Api\Action\User\ActivateAccount
      deserialize: false
      denormalization_context:
        groups: [user_activate]
      openapi_context:
        summary: Activate a user account
